name: Release Build

on:
  push:
    branches: [ 'release/*', 'releases/*' ]
  release:
    types: [created]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: iss

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23' # Adjust version as needed

      - name: Build with Maven
        shell: powershell
        run: C:\.mvn\apache-maven-3.9.9\bin\mvn clean install

      - name: Get Maven project details
        shell: powershell
        id: maven_info
        run: |
          echo "VERSION=$(C:\.mvn\apache-maven-3.9.9\bin\mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "FINAL_NAME=$(C:\.mvn\apache-maven-3.9.9\bin\mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "BUILD_DIR=$(C:\.mvn\apache-maven-3.9.9\bin\mvn help:evaluate -Dexpression=project.build.directory -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Build Installer
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" `
          "${{ github.workspace }}\clientsetup.iss" `
          "/DJarFile=${{ env.FINAL_NAME }}-jar-with-dependencies.jar" `
          "/DSourcePath=${{ env.BUILD_DIR }}" `
          "/DAppVersion=${{ env.VERSION }}"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/release/')
        with:
          tag_name: v${{ steps.maven_info.outputs.VERSION }}
          name: Release v${{ steps.maven_info.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            ${{ steps.maven_info.outputs.BUILD_DIR }}/${{ steps.maven_info.outputs.FINAL_NAME }}-jar-with-dependencies.jar
            ${{ steps.maven_info.outputs.BUILD_DIR }}/Output/*.exe
          token: ${{ secrets.GITHUB_TOKEN }}